-- Add user preference fields
alter table if exists public.users
  add column if not exists dietary_preferences text[] default '{}'::text[];

alter table if exists public.users
  add column if not exists allergens text[] default '{}'::text[];

-- Ensure menu item names are unique to avoid duplicate seeding
create unique index if not exists menu_items_name_key on public.menu_items (name);

-- Seed diverse menu items (50) with idempotency
insert into public.menu_items (name, description, price, category, image, is_veg, cuisine, spice_level, allergens, nutritional_info, is_available, ingredients, average_rating, review_count, preparation_time)
values
  ('Margherita Pizza', 'Classic cheese and tomato pizza with basil', 199, 'Main Course', 'https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg', true, 'Continental', 1, array['dairy'], '{"calories":300,"protein":12,"carbs":34,"fat":12}', true, array['Flour','Tomato','Cheese','Basil'], 4.2, 12, 20),
  ('Farmhouse Pizza', 'Loaded with veggies and mozzarella', 249, 'Main Course', 'https://images.pexels.com/photos/2741458/pexels-photo-2741458.jpeg', true, 'Continental', 2, array['dairy','gluten'], '{"calories":340,"protein":14,"carbs":40,"fat":14}', true, array['Flour','Cheese','Capsicum','Onion','Sweet Corn'], 4.4, 18, 22),
  ('Chicken Pepperoni Pizza', 'Spicy pepperoni with cheese', 279, 'Main Course', 'https://images.pexels.com/photos/4109081/pexels-photo-4109081.jpeg', false, 'Continental', 3, array['dairy','gluten'], '{"calories":380,"protein":20,"carbs":38,"fat":18}', true, array['Flour','Cheese','Pepperoni','Tomato'], 4.5, 25, 22),
  ('Veg Hakka Noodles', 'Stir-fried noodles with mixed vegetables', 120, 'Main Course', 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg', true, 'Chinese', 2, array['gluten','soy'], '{"calories":260,"protein":8,"carbs":46,"fat":6}', true, array['Noodles','Cabbage','Carrot','Soy Sauce'], 4.1, 20, 15),
  ('Chicken Fried Rice', 'Wok-tossed rice with chicken and eggs', 140, 'Main Course', 'https://images.pexels.com/photos/3577430/pexels-photo-3577430.jpeg', false, 'Chinese', 2, array['egg','soy'], '{"calories":320,"protein":16,"carbs":45,"fat":8}', true, array['Rice','Chicken','Egg','Soy Sauce'], 4.3, 22, 15),
  ('Veg Fried Rice', 'Classic fried rice with fresh veggies', 110, 'Main Course', 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg', true, 'Chinese', 1, array['soy'], '{"calories":280,"protein":7,"carbs":48,"fat":6}', true, array['Rice','Carrot','Beans','Soy Sauce'], 4.0, 15, 14),
  ('Idli Sambar', 'Steamed rice cakes with lentil stew', 60, 'Breakfast', 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg', true, 'South Indian', 1, array[]::text[], '{"calories":220,"protein":8,"carbs":42,"fat":3}', true, array['Rice','Lentils','Spices'], 4.6, 35, 10),
  ('Pongal', 'Comforting rice and lentil dish with ghee', 70, 'Breakfast', 'https://images.pexels.com/photos/1458694/pexels-photo-1458694.jpeg', true, 'South Indian', 1, array['dairy'], '{"calories":240,"protein":9,"carbs":38,"fat":5}', true, array['Rice','Moong Dal','Pepper','Cumin','Ghee'], 4.2, 16, 12),
  ('Vada Pav', 'Mumbai-style potato patty in a bun', 40, 'Appetizer', 'https://images.pexels.com/photos/5409020/pexels-photo-5409020.jpeg', true, 'Indian', 3, array['gluten'], '{"calories":280,"protein":5,"carbs":36,"fat":12}', true, array['Potato','Bun','Chutney','Spices'], 4.3, 28, 8),
  ('Pani Puri', 'Crispy puris with tangy water', 50, 'Appetizer', 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg', true, 'Indian', 2, array['gluten'], '{"calories":180,"protein":4,"carbs":28,"fat":6}', true, array['Semolina','Potato','Mint','Tamarind'], 4.5, 30, 10),
  ('Masala Chai', 'Spiced Indian tea with milk', 20, 'Beverages', 'https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg', true, 'Indian', 0, array['dairy'], '{"calories":60,"protein":2,"carbs":8,"fat":2}', true, array['Tea','Milk','Spices'], 4.8, 50, 5),
  ('Cold Coffee', 'Iced coffee with milk and sugar', 60, 'Beverages', 'https://images.pexels.com/photos/976726/pexels-photo-976726.jpeg', true, 'Continental', 0, array['dairy'], '{"calories":120,"protein":3,"carbs":18,"fat":4}', true, array['Coffee','Milk','Sugar','Ice'], 4.2, 14, 4),
  ('Chicken Roll', 'Grilled chicken wrap with veggies', 90, 'Appetizer', 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg', false, 'Indian', 2, array['gluten'], '{"calories":300,"protein":18,"carbs":28,"fat":10}', true, array['Chicken','Wheat Roti','Onion','Mint'], 4.1, 12, 10),
  ('Paneer Roll', 'Paneer tikka wrap', 85, 'Appetizer', 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg', true, 'Indian', 2, array['gluten','dairy'], '{"calories":290,"protein":15,"carbs":28,"fat":9}', true, array['Paneer','Wheat Roti','Onion','Mint'], 4.2, 13, 10),
  ('Tomato Soup', 'Creamy tomato soup with herbs', 70, 'Appetizer', 'https://images.pexels.com/photos/3730955/pexels-photo-3730955.jpeg', true, 'Continental', 1, array['dairy'], '{"calories":120,"protein":3,"carbs":16,"fat":4}', true, array['Tomato','Cream','Herbs'], 4.0, 9, 8),
  ('Sweet Lassi', 'Sweetened yogurt drink', 50, 'Beverages', 'https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg', true, 'Indian', 0, array['dairy'], '{"calories":180,"protein":6,"carbs":24,"fat":6}', true, array['Yogurt','Sugar','Cardamom'], 4.4, 17, 3),
  ('Gulab Jamun', 'Milk-solid dumplings in syrup', 60, 'Desserts', 'https://images.pexels.com/photos/1627861/pexels-photo-1627861.jpeg', true, 'Indian', 0, array['dairy','gluten'], '{"calories":220,"protein":4,"carbs":36,"fat":8}', true, array['Milk Solids','Flour','Sugar Syrup'], 4.6, 26, 5),
  ('Brownie', 'Chocolate brownie with nuts', 80, 'Desserts', 'https://images.pexels.com/photos/45202/chocolate-brownie-dessert-cake-45202.jpeg', true, 'Continental', 0, array['gluten','nuts','dairy'], '{"calories":320,"protein":5,"carbs":40,"fat":15}', true, array['Flour','Cocoa','Butter','Walnuts'], 4.3, 11, 7),
  ('Chicken Biryani', 'Aromatic basmati rice with chicken', 150, 'Main Course', 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg', false, 'Indian', 3, array['dairy'], '{"calories":450,"protein":25,"carbs":60,"fat":15}', true, array['Chicken','Rice','Spices','Yogurt'], 4.5, 40, 25),
  ('Veg Biryani', 'Mixed vegetable biryani', 130, 'Main Course', 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg', true, 'Indian', 2, array['dairy'], '{"calories":400,"protein":12,"carbs":62,"fat":12}', true, array['Rice','Vegetables','Spices','Yogurt'], 4.2, 22, 25),
  ('Paneer Butter Masala', 'Creamy tomato gravy with paneer', 140, 'Main Course', 'https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg', true, 'Indian', 2, array['dairy'], '{"calories":320,"protein":18,"carbs":15,"fat":22}', true, array['Paneer','Tomato','Cream','Spices'], 4.4, 31, 20),
  ('Butter Naan', 'Soft leavened flatbread', 35, 'Main Course', 'https://images.pexels.com/photos/590822/pexels-photo-590822.jpeg', true, 'Indian', 0, array['gluten','dairy'], '{"calories":150,"protein":4,"carbs":26,"fat":3}', true, array['Flour','Butter','Yeast'], 4.3, 27, 6),
  ('Tandoori Roti', 'Whole wheat flatbread', 20, 'Main Course', 'https://images.pexels.com/photos/590822/pexels-photo-590822.jpeg', true, 'Indian', 0, array['gluten'], '{"calories":120,"protein":3,"carbs":22,"fat":2}', true, array['Whole Wheat Flour','Water','Salt'], 4.1, 19, 5),
  ('Dal Tadka', 'Yellow lentils tempered with spices', 110, 'Main Course', 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg', true, 'Indian', 2, array[]::text[], '{"calories":250,"protein":12,"carbs":30,"fat":8}', true, array['Lentils','Tomato','Onion','Spices'], 4.5, 29, 18),
  ('Chole Bhature', 'Spicy chickpeas with fried bread', 120, 'Main Course', 'https://images.pexels.com/photos/5638714/pexels-photo-5638714.jpeg', true, 'Indian', 3, array['gluten'], '{"calories":520,"protein":14,"carbs":62,"fat":20}', true, array['Chickpeas','Flour','Spices','Oil'], 4.4, 33, 20),
  ('Pav Bhaji', 'Butter tossed mixed veg curry with pav', 100, 'Main Course', 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg', true, 'Indian', 2, array['gluten','dairy'], '{"calories":380,"protein":9,"carbs":50,"fat":14}', true, array['Vegetables','Butter','Pav','Spices'], 4.6, 45, 18),
  ('Dosa', 'Crisp rice-lentil crepe', 70, 'Breakfast', 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg', true, 'South Indian', 1, array[]::text[], '{"calories":230,"protein":6,"carbs":40,"fat":4}', true, array['Rice','Lentils','Oil'], 4.7, 38, 12),
  ('Uttapam', 'Thick pancake with toppings', 80, 'Breakfast', 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg', true, 'South Indian', 1, array[]::text[], '{"calories":260,"protein":7,"carbs":42,"fat":5}', true, array['Rice','Lentils','Onion','Tomato'], 4.3, 18, 14),
  ('Sambar Rice', 'Rice mixed with tangy sambar', 90, 'Main Course', 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg', true, 'South Indian', 2, array[]::text[], '{"calories":320,"protein":10,"carbs":56,"fat":6}', true, array['Rice','Lentils','Tamarind','Vegetables'], 4.2, 16, 15),
  ('Curd Rice', 'Comforting rice with yogurt and tempering', 85, 'Main Course', 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg', true, 'South Indian', 0, array['dairy'], '{"calories":300,"protein":9,"carbs":48,"fat":5}', true, array['Rice','Yogurt','Tempering'], 4.1, 12, 10),
  ('Chicken Tikka', 'Grilled marinated chicken', 160, 'Appetizer', 'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg', false, 'Indian', 3, array['dairy'], '{"calories":200,"protein":28,"carbs":5,"fat":7}', true, array['Chicken','Yogurt','Spices'], 4.6, 27, 20),
  ('Paneer Tikka', 'Grilled marinated paneer', 150, 'Appetizer', 'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg', true, 'Indian', 2, array['dairy'], '{"calories":220,"protein":18,"carbs":8,"fat":10}', true, array['Paneer','Yogurt','Spices'], 4.5, 23, 18),
  ('Veg Sandwich', 'Grilled sandwich with veggies and sauce', 60, 'Appetizer', 'https://images.pexels.com/photos/1600711/pexels-photo-1600711.jpeg', true, 'Continental', 0, array['gluten','dairy'], '{"calories":260,"protein":7,"carbs":34,"fat":8}', true, array['Bread','Veggies','Cheese','Sauce'], 4.0, 10, 7),
  ('Chicken Sandwich', 'Chicken sandwich with mayo', 75, 'Appetizer', 'https://images.pexels.com/photos/1600711/pexels-photo-1600711.jpeg', false, 'Continental', 0, array['gluten','egg'], '{"calories":300,"protein":16,"carbs":34,"fat":10}', true, array['Bread','Chicken','Mayo'], 4.1, 11, 7),
  ('Pasta Alfredo', 'Creamy white sauce pasta', 160, 'Main Course', 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg', true, 'Continental', 1, array['dairy','gluten'], '{"calories":420,"protein":12,"carbs":56,"fat":14}', true, array['Pasta','Cream','Cheese'], 4.2, 15, 16),
  ('Pasta Arrabbiata', 'Spicy tomato sauce pasta', 150, 'Main Course', 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg', true, 'Continental', 3, array['gluten'], '{"calories":380,"protein":10,"carbs":58,"fat":8}', true, array['Pasta','Tomato','Chili'], 4.1, 14, 16),
  ('Veg Momos', 'Steamed dumplings with veggies', 90, 'Appetizer', 'https://images.pexels.com/photos/60616/dumplings-asian-food-chinese-food-60616.jpeg', true, 'Chinese', 1, array['gluten','soy'], '{"calories":240,"protein":7,"carbs":36,"fat":6}', true, array['Flour','Cabbage','Carrot','Soy Sauce'], 4.2, 20, 12),
  ('Chicken Momos', 'Steamed dumplings with chicken', 110, 'Appetizer', 'https://images.pexels.com/photos/60616/dumplings-asian-food-chinese-food-60616.jpeg', false, 'Chinese', 1, array['gluten','soy'], '{"calories":260,"protein":12,"carbs":34,"fat":6}', true, array['Flour','Chicken','Soy Sauce'], 4.3, 22, 12),
  ('Egg Curry', 'Eggs simmered in spicy gravy', 110, 'Main Course', 'https://images.pexels.com/photos/4107752/pexels-photo-4107752.jpeg', false, 'Indian', 2, array['egg'], '{"calories":300,"protein":16,"carbs":14,"fat":18}', true, array['Eggs','Tomato','Onion','Spices'], 4.1, 12, 18),
  ('Veg Thali', 'Assorted vegetarian platter', 180, 'Main Course', 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg', true, 'Indian', 2, array['dairy','gluten'], '{"calories":650,"protein":20,"carbs":90,"fat":18}', true, array['Rice','Dal','Sabzi','Roti','Curd'], 4.4, 24, 20),
  ('Chicken Thali', 'Assorted non-veg platter', 220, 'Main Course', 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg', false, 'Indian', 3, array['gluten'], '{"calories":750,"protein":35,"carbs":85,"fat":25}', true, array['Rice','Chicken Curry','Roti','Salad'], 4.5, 28, 22),
  ('Lemonade', 'Fresh lemon drink', 30, 'Beverages', 'https://images.pexels.com/photos/1304647/pexels-photo-1304647.jpeg', true, 'Continental', 0, array[]::text[], '{"calories":40,"protein":0,"carbs":10,"fat":0}', true, array['Lemon','Water','Sugar','Mint'], 4.3, 19, 2),
  ('Mango Shake', 'Thick mango milkshake', 70, 'Beverages', 'https://images.pexels.com/photos/2647933/pexels-photo-2647933.jpeg', true, 'Indian', 0, array['dairy'], '{"calories":220,"protein":6,"carbs":38,"fat":5}', true, array['Mango','Milk','Sugar'], 4.6, 32, 3),
  ('Oreo Shake', 'Cookies and cream milkshake', 80, 'Beverages', 'https://images.pexels.com/photos/2647933/pexels-photo-2647933.jpeg', true, 'Continental', 0, array['dairy','gluten'], '{"calories":260,"protein":6,"carbs":42,"fat":7}', true, array['Milk','Oreo','Sugar'], 4.2, 13, 3),
  ('Chocolate Shake', 'Rich chocolate milkshake', 80, 'Beverages', 'https://images.pexels.com/photos/2647933/pexels-photo-2647933.jpeg', true, 'Continental', 0, array['dairy'], '{"calories":250,"protein":7,"carbs":40,"fat":7}', true, array['Milk','Cocoa','Sugar'], 4.3, 14, 3),
  ('Veg Puff', 'Baked puff pastry with veg filling', 35, 'Appetizer', 'https://images.pexels.com/photos/4109382/pexels-photo-4109382.jpeg', true, 'Continental', 1, array['gluten','dairy'], '{"calories":220,"protein":4,"carbs":24,"fat":12}', true, array['Flour','Butter','Vegetables'], 4.0, 9, 8),
  ('Egg Puff', 'Baked puff with egg filling', 40, 'Appetizer', 'https://images.pexels.com/photos/4109382/pexels-photo-4109382.jpeg', false, 'Continental', 1, array['gluten','egg','dairy'], '{"calories":240,"protein":7,"carbs":24,"fat":13}', true, array['Flour','Butter','Egg'], 4.1, 10, 8),
  ('Spring Rolls', 'Crispy veg spring rolls', 75, 'Appetizer', 'https://images.pexels.com/photos/302680/pexels-photo-302680.jpeg', true, 'Chinese', 2, array['gluten','soy'], '{"calories":260,"protein":6,"carbs":34,"fat":10}', true, array['Flour','Cabbage','Carrot','Soy Sauce'], 4.2, 16, 10),
  ('Chicken Lollipop', 'Fried chicken wings', 120, 'Appetizer', 'https://images.pexels.com/photos/4109128/pexels-photo-4109128.jpeg', false, 'Chinese', 3, array[]::text[], '{"calories":320,"protein":20,"carbs":10,"fat":20}', true, array['Chicken','Spices'], 4.4, 21, 12),
  ('Veg Burger', 'Veg patty burger with lettuce and tomato', 90, 'Main Course', 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg', true, 'Continental', 1, array['gluten','dairy'], '{"calories":340,"protein":9,"carbs":44,"fat":12}', true, array['Bun','Veg Patty','Cheese','Lettuce'], 4.1, 18, 12),
  ('Chicken Burger', 'Grilled chicken burger', 120, 'Main Course', 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg', false, 'Continental', 2, array['gluten','egg'], '{"calories":380,"protein":18,"carbs":46,"fat":14}', true, array['Bun','Chicken Patty','Mayo','Lettuce'], 4.2, 20, 12),
  ('French Fries', 'Crispy golden fries', 70, 'Appetizer', 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg', true, 'Continental', 0, array[]::text[], '{"calories":300,"protein":5,"carbs":40,"fat":12}', true, array['Potato','Oil','Salt'], 4.5, 45, 6),
  ('Peri Peri Fries', 'Spicy seasoned fries', 80, 'Appetizer', 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg', true, 'Continental', 2, array[]::text[], '{"calories":320,"protein":5,"carbs":40,"fat":14}', true, array['Potato','Oil','Spices'], 4.4, 26, 6),
  ('Grilled Sandwich', 'Grilled cheese sandwich', 70, 'Appetizer', 'https://images.pexels.com/photos/1600711/pexels-photo-1600711.jpeg', true, 'Continental', 0, array['gluten','dairy'], '{"calories":280,"protein":9,"carbs":32,"fat":12}', true, array['Bread','Cheese','Butter'], 4.1, 12, 7),
  ('Caramel Custard', 'Baked caramel custard', 60, 'Desserts', 'https://images.pexels.com/photos/302680/pexels-photo-302680.jpeg', true, 'Continental', 0, array['dairy','egg'], '{"calories":210,"protein":6,"carbs":28,"fat":8}', true, array['Milk','Egg','Sugar'], 4.3, 15, 8),
  ('Fruit Salad', 'Seasonal fruits bowl', 70, 'Desserts', 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg', true, 'Continental', 0, array[]::text[], '{"calories":180,"protein":3,"carbs":40,"fat":1}', true, array['Fruits','Honey','Mint'], 4.2, 10, 5),
  ('Club Sandwich', 'Triple-layered veg club sandwich', 100, 'Appetizer', 'https://images.pexels.com/photos/1600711/pexels-photo-1600711.jpeg', true, 'Continental', 0, array['gluten','dairy'], '{"calories":360,"protein":12,"carbs":46,"fat":14}', true, array['Bread','Cheese','Veggies','Sauce'], 4.2, 14, 10),
  ('Veg Manchurian', 'Veg balls in spicy sauce', 120, 'Main Course', 'https://images.pexels.com/photos/302680/pexels-photo-302680.jpeg', true, 'Chinese', 3, array['gluten','soy'], '{"calories":340,"protein":9,"carbs":38,"fat":14}', true, array['Cabbage','Flour','Soy Sauce','Chili'], 4.1, 16, 15),
  ('Chicken Manchurian', 'Chicken in spicy sauce', 150, 'Main Course', 'https://images.pexels.com/photos/302680/pexels-photo-302680.jpeg', false, 'Chinese', 3, array['soy'], '{"calories":380,"protein":20,"carbs":26,"fat":18}', true, array['Chicken','Soy Sauce','Chili'], 4.2, 18, 15),
  ('Veg Pulao', 'Fragrant rice with vegetables', 110, 'Main Course', 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg', true, 'Indian', 1, array[]::text[], '{"calories":320,"protein":8,"carbs":60,"fat":6}', true, array['Rice','Vegetables','Spices'], 4.0, 9, 18),
  ('Rava Dosa', 'Crispy semolina dosa', 80, 'Breakfast', 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg', true, 'South Indian', 1, array['gluten'], '{"calories":250,"protein":6,"carbs":44,"fat":5}', true, array['Semolina','Rice Flour','Spices'], 4.1, 12, 12)
on conflict (name) do nothing;


